// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: OpenApiCommonModelMessages.proto

package openapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- INTENSIVE COMMANDS 1 - 49
// --- COMMON API 50 - 69
type ProtoPayloadType int32

const (
	// common intensive
	ProtoPayloadType_PROTO_MESSAGE ProtoPayloadType = 5
	// common commands
	ProtoPayloadType_ERROR_RES       ProtoPayloadType = 50
	ProtoPayloadType_HEARTBEAT_EVENT ProtoPayloadType = 51
)

// Enum value maps for ProtoPayloadType.
var (
	ProtoPayloadType_name = map[int32]string{
		5:  "PROTO_MESSAGE",
		50: "ERROR_RES",
		51: "HEARTBEAT_EVENT",
	}
	ProtoPayloadType_value = map[string]int32{
		"PROTO_MESSAGE":   5,
		"ERROR_RES":       50,
		"HEARTBEAT_EVENT": 51,
	}
)

func (x ProtoPayloadType) Enum() *ProtoPayloadType {
	p := new(ProtoPayloadType)
	*p = x
	return p
}

func (x ProtoPayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoPayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_OpenApiCommonModelMessages_proto_enumTypes[0].Descriptor()
}

func (ProtoPayloadType) Type() protoreflect.EnumType {
	return &file_OpenApiCommonModelMessages_proto_enumTypes[0]
}

func (x ProtoPayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ProtoPayloadType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ProtoPayloadType(num)
	return nil
}

// Deprecated: Use ProtoPayloadType.Descriptor instead.
func (ProtoPayloadType) EnumDescriptor() ([]byte, []int) {
	return file_OpenApiCommonModelMessages_proto_rawDescGZIP(), []int{0}
}

// COMMON error codes 1 - 99
type ProtoErrorCode int32

const (
	ProtoErrorCode_UNKNOWN_ERROR           ProtoErrorCode = 1  // Generic error.
	ProtoErrorCode_UNSUPPORTED_MESSAGE     ProtoErrorCode = 2  // Message is not supported. Wrong message.
	ProtoErrorCode_INVALID_REQUEST         ProtoErrorCode = 3  // Generic error.  Usually used when input value is not correct.
	ProtoErrorCode_TIMEOUT_ERROR           ProtoErrorCode = 5  // Deal execution is reached timeout and rejected.
	ProtoErrorCode_ENTITY_NOT_FOUND        ProtoErrorCode = 6  // Generic error for requests by id.
	ProtoErrorCode_CANT_ROUTE_REQUEST      ProtoErrorCode = 7  // Connection to Server is lost or not supported.
	ProtoErrorCode_FRAME_TOO_LONG          ProtoErrorCode = 8  // Message is too large.
	ProtoErrorCode_MARKET_CLOSED           ProtoErrorCode = 9  // Market is closed.
	ProtoErrorCode_CONCURRENT_MODIFICATION ProtoErrorCode = 10 // Order is blocked (e.g. under execution) and change cannot be applied.
	ProtoErrorCode_BLOCKED_PAYLOAD_TYPE    ProtoErrorCode = 11 // Message is blocked by server or rate limit is reached.
)

// Enum value maps for ProtoErrorCode.
var (
	ProtoErrorCode_name = map[int32]string{
		1:  "UNKNOWN_ERROR",
		2:  "UNSUPPORTED_MESSAGE",
		3:  "INVALID_REQUEST",
		5:  "TIMEOUT_ERROR",
		6:  "ENTITY_NOT_FOUND",
		7:  "CANT_ROUTE_REQUEST",
		8:  "FRAME_TOO_LONG",
		9:  "MARKET_CLOSED",
		10: "CONCURRENT_MODIFICATION",
		11: "BLOCKED_PAYLOAD_TYPE",
	}
	ProtoErrorCode_value = map[string]int32{
		"UNKNOWN_ERROR":           1,
		"UNSUPPORTED_MESSAGE":     2,
		"INVALID_REQUEST":         3,
		"TIMEOUT_ERROR":           5,
		"ENTITY_NOT_FOUND":        6,
		"CANT_ROUTE_REQUEST":      7,
		"FRAME_TOO_LONG":          8,
		"MARKET_CLOSED":           9,
		"CONCURRENT_MODIFICATION": 10,
		"BLOCKED_PAYLOAD_TYPE":    11,
	}
)

func (x ProtoErrorCode) Enum() *ProtoErrorCode {
	p := new(ProtoErrorCode)
	*p = x
	return p
}

func (x ProtoErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_OpenApiCommonModelMessages_proto_enumTypes[1].Descriptor()
}

func (ProtoErrorCode) Type() protoreflect.EnumType {
	return &file_OpenApiCommonModelMessages_proto_enumTypes[1]
}

func (x ProtoErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ProtoErrorCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ProtoErrorCode(num)
	return nil
}

// Deprecated: Use ProtoErrorCode.Descriptor instead.
func (ProtoErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_OpenApiCommonModelMessages_proto_rawDescGZIP(), []int{1}
}

var File_OpenApiCommonModelMessages_proto protoreflect.FileDescriptor

const file_OpenApiCommonModelMessages_proto_rawDesc = "" +
	"\n" +
	" OpenApiCommonModelMessages.proto*I\n" +
	"\x10ProtoPayloadType\x12\x11\n" +
	"\rPROTO_MESSAGE\x10\x05\x12\r\n" +
	"\tERROR_RES\x102\x12\x13\n" +
	"\x0fHEARTBEAT_EVENT\x103*\xf0\x01\n" +
	"\x0eProtoErrorCode\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x01\x12\x17\n" +
	"\x13UNSUPPORTED_MESSAGE\x10\x02\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x03\x12\x11\n" +
	"\rTIMEOUT_ERROR\x10\x05\x12\x14\n" +
	"\x10ENTITY_NOT_FOUND\x10\x06\x12\x16\n" +
	"\x12CANT_ROUTE_REQUEST\x10\a\x12\x12\n" +
	"\x0eFRAME_TOO_LONG\x10\b\x12\x11\n" +
	"\rMARKET_CLOSED\x10\t\x12\x1b\n" +
	"\x17CONCURRENT_MODIFICATION\x10\n" +
	"\x12\x18\n" +
	"\x14BLOCKED_PAYLOAD_TYPE\x10\vBW\n" +
	"(com.xtrader.protocol.proto.commons.modelB\x1cContainerCommonModelMessagesP\x01Z\b/openapi\xa0\x01\x01"

var (
	file_OpenApiCommonModelMessages_proto_rawDescOnce sync.Once
	file_OpenApiCommonModelMessages_proto_rawDescData []byte
)

func file_OpenApiCommonModelMessages_proto_rawDescGZIP() []byte {
	file_OpenApiCommonModelMessages_proto_rawDescOnce.Do(func() {
		file_OpenApiCommonModelMessages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_OpenApiCommonModelMessages_proto_rawDesc), len(file_OpenApiCommonModelMessages_proto_rawDesc)))
	})
	return file_OpenApiCommonModelMessages_proto_rawDescData
}

var file_OpenApiCommonModelMessages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_OpenApiCommonModelMessages_proto_goTypes = []any{
	(ProtoPayloadType)(0), // 0: ProtoPayloadType
	(ProtoErrorCode)(0),   // 1: ProtoErrorCode
}
var file_OpenApiCommonModelMessages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_OpenApiCommonModelMessages_proto_init() }
func file_OpenApiCommonModelMessages_proto_init() {
	if File_OpenApiCommonModelMessages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_OpenApiCommonModelMessages_proto_rawDesc), len(file_OpenApiCommonModelMessages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OpenApiCommonModelMessages_proto_goTypes,
		DependencyIndexes: file_OpenApiCommonModelMessages_proto_depIdxs,
		EnumInfos:         file_OpenApiCommonModelMessages_proto_enumTypes,
	}.Build()
	File_OpenApiCommonModelMessages_proto = out.File
	file_OpenApiCommonModelMessages_proto_goTypes = nil
	file_OpenApiCommonModelMessages_proto_depIdxs = nil
}
